### ISSUE TITLE
error when downloading jobs

### ISSUE THREAD

**Issue by xueqixuan** [MWATelescope/manta-ray-client#11]
I used the given example
**obs_id=1191828584, job_type=c, timeres=20, freqres=20, edgewidth=80, conversion=ms, allowmissing=true, flagdcchannels=true**
and
**obs_id=1191828584, job_type=d, download_type=vis
obs_id=1191828528, job_type=d, download_type=vis_meta**
and the program ended with error message as：
**Error: Permission to access 1191828584 denied, data still under an embargo.; Job id: 3432 type: 0 params: {u'conversion': u'ms', u'freqres': u'20', u'obs_id': u'1191828584', u'flags': [u'-allowmissing', u'-flagdcchannels'], u'timeres': u'20', u'edgewidth': u'80'}**
I wonder what mistake there is.
Could you please explain it. Thanks.

**Comment by gsleap** [comment]
Hi,
The error you are getting is that the observation id used in the examples in the README file are under embargo. Data taken by the MWA is under embargo for 18 months before it is publicly available. Until then, the data is only accessible by the principal investigator of the telescope time proposal.  I have modified the README to use a publicly available observation id. Sorry for the confusion!

**Comment by xueqixuan** [comment]
Thanks
