### ISSUE TITLE
How can I get mwa job information

### ISSUE THREAD

**Issue by xueqixuan** [MWATelescope/manta-ray-client#12]
I am doing a scheduling research and I need the mwa job data as the testing set
So in order to get the data, can I use the given example as: 
**obs_id=1110103576, job_type=d, download_type=vis
obs_id=1110105120, job_type=d, download_type=vis_meta**
and run the mwa_client.py to get the data I need? Or are there other ways
Thanks

**Comment by gsleap** [comment]
The above csv file example will download the raw visibilities for obsid 1110103576 and for 1110105120 it will download just the metafits file (containing metadata only).  If this is not what you are after Can you please send an email to asvo_support at mwatelescope.org and provide more details on what type of data you are after.  Thanks!
