### ISSUE TITLE
allow 0.5 sec time resolution during the cottering stage

### ISSUE THREAD

**Issue by PaulHancock** [MWATelescope/manta-ray-client#14]
Observation 1175210528 has a native resolution of 0.5sec / 40khz and I want to download a measurement set at this resolution

the mwa_client doesn't allow me to specify 0.5sec time resolution. I have set timeres=0.5 in the csv file that I submit but I get the following error:
```
Connecting to ASVO
Connected to ASVO
{"error_code": 0, "error": "Time Resolution: Not of type integer"}
```

I could presumably just leave timeres blank and get the 'native' resolution that I desire, however it is painful to code around this possibility when writing job scripts.

**Comment by PaulHancock** [comment]
This also occurs when trying to download data from the ASVO website. The page allows me to select 0.5sec as an option for the time averaging (using the up/down buttons on the field), but when I press submit I get an error to say that it needs to be an integer.

**Comment by gsleap** [comment]
Hi Paul, we have a fix for this and are just awaiting Pawsey to update to a more recent git version so we can deploy it.
