### ISSUE TITLE
ASVO query table doesn't indicate embargoed status

### ISSUE THREAD

**Issue by PaulHancock** [MWATelescope/manta-ray-client#15]
On the ASVO query page all observations can be queried but it is not possible to tell if a particular observation is available for download. When the job request is submitted I get errors about the data being under embargo. It would be great to see which data are embargoed without having to submit job requests.

**Comment by davepallot** [comment]
Should not be hard to add a non-persistent view of the embargo date based on the query results i.e. obsid+18months

**Comment by harrisonbarlow** [comment]
Closing, this has been fixed in a recent release
