### ISSUE TITLE
ASVO query page ignores "to" date when no "from" date is specified

### ISSUE THREAD

**Issue by PaulHancock** [MWATelescope/manta-ray-client#17]
I want to find all observations before 2016-01-01. If I simply enter that into the "to" date field, no date filters are being applied to the data. I need to also specify a "from" date before the filter is being applied.

**Comment by gsleap** [comment]
Hi Paul, This issue is already fixed in the next release of the MWA ASVO website, which we are just awaiting Pawsey to update git for us before we deploy.
