### ISSUE TITLE
ASVO query returns obsids that have no files associated with them

### ISSUE THREAD

**Issue by PaulHancock** [MWATelescope/manta-ray-client#18]
The obsid 1129021248 has no files associated with it according to the metadata server.

When I find this obsid in the ASVO query page it lists the "size" as 63360 bytes, but gives no flags to suggest that this obsid has no data associated with it. It is not until I try to download data from this observation that I'm told that there is not available data.

It would be good to have an option in the ASVO query to exclude results that have no files (and have it on by default), and when this option is off, to have another column in the returned table that indicates that there are no files available for download.

**Comment by gsleap** [comment]
Yes, this is a good point. We're looking into this and probably will modify our query to only return observations of "good" quality and that have some gpubox files.

**Comment by gsleap** [comment]
Fixed in the new (2021) UI
