### ISSUE TITLE
Could you please provide more items

### ISSUE THREAD

**Issue by xueqixuan** [MWATelescope/manta-ray-client#19]
Could you please provide more examples as:
**obs_id=1110103576, job_type=d, download_type=vis
obs_id=1110105120, job_type=d, download_type=vis_meta**
So I can downloads more data.
Thanks

**Comment by gsleap** [comment]
Hi,
You should be able to use the "query" page on the MWA ASVO website to find more observations to download. For example, in the search parameters, use G0001 as the "Project" and it will provide thousands of observations to try.

Good luck!
