### ISSUE TITLE
Search updates

### ISSUE THREAD

**Issue by awicenec** [MWATelescope/manta-ray-client#20]
We need to have two things in the search interface: 

One is a name resolver search box, I.e. enter the name of an object and call the Simbad name resolver to get the coordinates.

The other one is to support sexagesimal coordinate input rather than just degrees. There is ready-to-use code around for that.

**Comment by gsleap** [comment]
Closing this here as it is tracked in [issue 1 of manta-ray repo](https://github.com/ICRAR/manta-ray/issues/1).
