### ISSUE TITLE
Question: What does usepcentre actually do?

### ISSUE THREAD

**Issue by PaulHancock** [MWATelescope/manta-ray-client#23]
I have been using the following option as part of our pipeline:
`usepcentre: Centre on pointing centre.`

My assumption is that this will cause the following to be run on the data set:
`chgcentre -minw -shiftback obs.ms`

Can you verify this or indicate what `usepcentre` actually does?

**Comment by gsleap** [comment]
Hi Paul- sorry for leaving this issue open for an embarrassingly long time. "usepcentre" is just a cotter option.  Here is the help from cotter:
"-usepcenter: Centre on pointing centre"

So basically it ignores the phase centre settings of your observation and will use the (tile) pointing center instead.

If you need any more detail than that you may need to ask Andre!
