### ISSUE TITLE
Make sure timeres is not integer

### ISSUE THREAD

**Issue by dlakaplan** [MWATelescope/manta-ray-client#3]
Current documentation is:
`timeres=< integer >`
but we should be able to allow for 0.5s time resolution (and maybe more later).  I don't know if this is actually in the parser (a quick search wasn't obvious) but it would be good to confirm.

**Comment by davepallot** [comment]
Just a doco change as it can accept floating point timeres.

**Comment by dlakaplan** [comment]
Sounds good.
