### ISSUE TITLE
can not submit jobs

### ISSUE THREAD

**Issue by shaoguangleo** [MWATelescope/manta-ray-client#36]
Dear @gsleap @vesix1992 , glad to see the MWA ASVO is coming back for processing jobs.

I am wondering if I can submit to a job now or still need wait some time, cause when I submit jobs,
it pops up the following warning:

> manta-ray-client version 1.2.0
Connecting to MWA ASVO (asvo.mwatelescope.org:8778)...
HTTPSConnectionPool(host='asvo.mwatelescope.org', port=8778): Max retries exceeded with url: /api/login (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb1f2bb37b8>: Failed to establish a new connection: [Errno 111] Connection refused',))

I've upgraded to the latest version of mwa_client , and built it using the master branch.

Any suggestions?

**Comment by harrisonbarlow** [comment]
Hi Shaoguang,

Port 8778 is not used by the new version of the manta-ray-client (it is now 443 by default). Do you have an environment variable set (MWA_ASVO_PORT)? If so, just unset the environment variable, and it should use the correct port.

Cheers, I'll send you an email to give an update on ASVO generally.

**Comment by shaoguangleo** [comment]
Thanks Harrison @vesix1992 .
That makes sense.
Although I build the latest version, it points to the former file when I run this command.

Will close this issue. Sorry for the disruption.
