### ISSUE TITLE
Only obsid.ms directroy will be downloaded with the job type of Conversion 

### ISSUE THREAD

**Issue by bazhaoyu** [MWATelescope/manta-ray-client#37]
Hi, I submitted and downloaded the MWA data by mwa_client in the normal way:
mwa_client -c csvfile -d . -w $JOBID
the example of commands in csvfile:
obs_id=$obsid, job_type=c, timeres=8, freqres=40, edgewidth=80, conversion=ms, calibrate=false, allowmissing=true, flagdcchannels=true

But I found only $obsid.ms directory was downloaded. Would you mind letting me know how can I download the corresponding file of $obsid.metafits? Because several years ago, these two contents (the $obsid.ms and $obsid.metafits) could be downloaded simultaneously, if I remember rightly.

**Comment by gsleap** [comment]
Hi Dan, sorry for the delayed reply on this! The metafits file is now included in the downloaded files. Cheers
