### ISSUE TITLE
Add defaults for parameters

### ISSUE THREAD

**Issue by dlakaplan** [MWATelescope/manta-ray-client#4]
Could you please add defaults for as many parameters as have them?  This could be both in `README.md` and in the output of the `--help`

**Comment by davepallot** [comment]
It's the defaults directly from cotter, but a good idea to add them as help.

**Comment by dlakaplan** [comment]
Yes, if you are trying to expand beyond the standard cotter-sphere of if people don't know what cotter does for some of the more obscure parameters.
